// Generated by wrangler types or manually maintained.
// Run `npm run cf-typegen` to regenerate.

interface Env {
  GRIDER_CONTAINER: DurableObjectNamespace;
  TSANGHI_TOKEN_01: string;
  TSANGHI_TOKEN_02: string;
  JWT_SECRET_KEY: string;
}
