// Generated by wrangler types or manually maintained.
// Run `npm run cf-typegen` to regenerate.

interface Env {
  GRIDER_CONTAINER: DurableObjectNamespace;
  TICKFLOW_API_KEY: string;
  JWT_SECRET_KEY: string;
}
